<?
$PERM["obratnaya-svyaz"]["2"]="D";
$PERM["obratnaya-svyaz"]["5"]="D";
$PERM["obratnaya-svyaz"]["3"]="D";
$PERM["obratnaya-svyaz"]["4"]="D";
$PERM["obratnaya-svyaz"]["8"]="X";
$PERM["obratnaya-svyaz"]["6"]="X";
$PERM["obratnaya-svyaz"]["7"]="X";
?>